apiVersion: apps/v1
kind: Deployment
metadata:
  name: campus-app
  namespace: dev
  labels:
    app: campus-app
    environment: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: campus-app
  template:
    metadata:
      labels:
        app: campus-app
        environment: dev
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: campus-app
          image: 395671099988.dkr.ecr.ap-south-1.amazonaws.com/campus-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: campus-app-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
